### ISSUE TITLE
orthographe vue /tutorial

### ISSUE THREAD

**Issue by JulieRaymond** [WildCodeSchool-2023-09/2023-09-PHP-Bordeaux-P2-Escape-game#40]
Petit détail mais l'orthographe de la page /tutorial : 

- regardez pas regarder
- cacher pas cachés
- français suivi de "next" au lieu de "suivant", il faut garder une cohérence linguistique :)

![Capture d’écran 2023-11-21 à 09 39 09](https://github.com/WildCodeSchool-2023-09/2023-09-PHP-Bordeaux-P2-Escape-game/assets/122172605/8ce943f1-8a35-4dc5-bf2a-747b81050e3b)

**Comment by JulieRaymond** [comment]
ici aussi "bloqué" pas blocker:
![Capture d’écran 2023-11-21 à 09 42 11](https://github.com/WildCodeSchool-2023-09/2023-09-PHP-Bordeaux-P2-Escape-game/assets/122172605/df70291e-684e-4885-9b67-dceb12814a7d)

**Comment by samiAH98** [comment]
Correction des orthographes!
