### ISSUE TITLE
password min

### ISSUE THREAD

**Issue by Phalenopsis** [WildCodeSchool-2023-09/2023-09-PHP-Bordeaux-P2-Escape-game#43]
J'ai réussi à créer un compte avec seulement 4 caractères en mot de passe (que des lettres)

-> J'ai créé un compte normalement
-> j'avais oublié mon mot de passe
-> j'ai créé un autre compte
-> le message "le mot de passe gniagnia 8 caractères gniagnia..." n'est pas apparu
-> j'ai créé un mot de passe à 4 caractères et j'ai pu me connecter avec

**Comment by Phalenopsis** [comment]
en fait ça marche même en créant directement un mot de passe simple

**Comment by Melprcllr** [comment]
Réglé par Adeline 👌🏽
