### ISSUE TITLE
Vue /win

### ISSUE THREAD

**Issue by JulieRaymond** [WildCodeSchool-2023-09/2023-09-PHP-Bordeaux-P2-Escape-game#44]
Vous avez pas respecté clothilde mdr 😂 elle est toute ratatinée ! 

Je n'ai pas mon score final sur la page 

![Capture d’écran 2023-11-21 à 09 49 03](https://github.com/WildCodeSchool-2023-09/2023-09-PHP-Bordeaux-P2-Escape-game/assets/122172605/09efc3d7-b62b-47a3-899b-04d2aeb189bc)

**Comment by Jojopok** [comment]
Grave haha , c'est réglé :) !
