### ISSUE TITLE
retour

### ISSUE THREAD

**Issue by JulieRaymond** [WildCodeSchool-2023-09/2023-09-PHP-Bordeaux-P2-Escape-game#46]
Un bouton retour serait plus logique sur vos pages :) 

Car accueil ça fait bizarre par exemple quand on est sur la page classement, on voudrait plutôt retourner sur la page précédente plutôt que cliquer sur accueil.

![Capture d’écran 2023-11-21 à 09 55 22](https://github.com/WildCodeSchool-2023-09/2023-09-PHP-Bordeaux-P2-Escape-game/assets/122172605/058813a6-726d-4fe5-ace7-ffa3f91fd514)

**Comment by Jojopok** [comment]
Fait
