### ISSUE TITLE
Tuto-indices-end

### ISSUE THREAD

**Issue by Phalenopsis** [WildCodeSchool-2023-09/2023-09-PHP-Bordeaux-P2-Escape-game#47]
Dans l'explication, à la dernière info, je m'attendais à ce que mon dernier clic ferme la fenêtre. Ce n'est pas fluide de devoir cliquer sur la croix pour la fermer. Peut-être qu'un bouton "fermer" serait le bienvenu.
![Capture d'écran 2023-11-21 095441](https://github.com/WildCodeSchool-2023-09/2023-09-PHP-Bordeaux-P2-Escape-game/assets/102463918/32fa9773-c04e-44c7-b7c8-e955655da53d)

**Comment by samiAH98** [comment]
Ajout d'un bouton "fermer"!
