### ISSUE TITLE
Suggestion : Désactiver mauvaise réponse une fois qu'on l'a sélectionnée

### ISSUE THREAD

**Issue by Phalenopsis** [WildCodeSchool-2023-09/2023-09-PHP-Bordeaux-P2-Escape-game#50]
![Capture d'écran 2023-11-21 100737](https://github.com/WildCodeSchool-2023-09/2023-09-PHP-Bordeaux-P2-Escape-game/assets/102463918/f9b5efb3-4c83-4daf-83ce-363425604043)
Ce serait pas mal si les mauvaises réponses pouvaient se désactiver après qu'on les ait choisies (histoire de ne pas faire comme ce pauvre Marthy)

**Comment by Jojopok** [comment]
Marty est nul :')

**Comment by Jojopok** [comment]
Fait
