### ISSUE TITLE
pseudo dupliqué

### ISSUE THREAD

**Issue by Phalenopsis** [WildCodeSchool-2023-09/2023-09-PHP-Bordeaux-P2-Escape-game#52]
dans la page : /plan?scene=scene2&plan=plan4

le peudo est dupliqué (comme la clé) :
![Capture d'écran 2023-11-21 101351](https://github.com/WildCodeSchool-2023-09/2023-09-PHP-Bordeaux-P2-Escape-game/assets/102463918/433db84f-df2d-40fb-98de-a99af1bcca91)

**Comment by Melprcllr** [comment]
c'est fait
