### ISSUE TITLE
Rejouabilité

### ISSUE THREAD

**Issue by Phalenopsis** [WildCodeSchool-2023-09/2023-09-PHP-Bordeaux-P2-Escape-game#53]
Après avoir fini une partie, si je veux rejouer, je me retrouve à l'entrée avec la clé déjà dans l'inventaire et mon score qui est toujours à -1200 et des brouettes

**Comment by Phalenopsis** [comment]
Cela est valable même après m'être déconnecté et reconnecté avec le même compte

**Comment by samiAH98** [comment]
fini

**Comment by samiAH98** [comment]
fini
